### ISSUE TITLE
意思是 Python 版的 bug 不修了吗？

### ISSUE THREAD

**Issue by ouuan** [zyf722/nShogi#1]
qaq

**Comment by zyf722** [comment]
不（~~tou~~）修（~~lan~~）了，反正判断棋子能否移动的核心部分在 Lua 版本里已经写了，再加上这个写的实在太烂，改起来也很麻烦，所以再维护这个也没多大意义。
PS: 我记得 Github 上面有一个专门给 Python 的开发的 [将棋库](https://github.com/gunyarakun/python-shogi)，可以参考。
